on:
  pull_request:
  issue_comment:
    types: [created]

name: Formatting

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
      - name: Checkout the pull request code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr checkout ${{ github.event.issue.number }}
      - name: Report problems
        if: ${{ github.event.type == "PullRequestEvent" }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ `git status -s | wc -l` -ne 0 ]
          then gh pr comment ${{ github.event.number }} --body \
          ":red_square: &nbsp;Commit ${{ github.event.pull_request.head.sha }} requires formatting!\
          "$'\n\n'"Required formatting changes summary:\
          "$'\n```\n'"`git diff --stat`"$'\n```'
          else gh pr comment ${{ github.event.number }} --body \
          ":green_circle: &nbsp;Commit ${{ github.event.pull_request.head.sha }} is formatted properly."
          fi
      - name: Commit fixes
        if: ${{ github.event.type == "IssueCommentEvent" && github.event.issue.pull_request && (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER' || github.event.issue.user.id == github.event.comment.user.id) && startsWith(github.event.comment.body, '/format') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ `git status -s | wc -l` -ne 0 ] ; then
            git config --local user.name "$GITHUB_ACTOR"
            git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git commit -a -m "automatic formatting" -m "triggered by @$GITHUB_ACTOR on PR #${{ github.event.issue.number }}"
            if git push
            then gh pr comment ${{ github.event.issue.number }} --body \
              ":heavy_check_mark: auto-formatting triggered by [this comment](${{ github.event.comment.html_url }}) succeeded, commited as `git rev-parse HEAD`"
            else gh pr comment ${{ github.event.issue.number }} --body \
              ":x: auto-formatting triggered by [this comment](${{ github.event.comment.html_url }}) failed, perhaps someone pushed to the PR in the meantime?"
            fi
          else
            echo "No changes, all good!"
          fi
